package com.hmpay.remittance

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(RemittanceConfigurationProperties::class)
class RemittanceConfiguration
