package com.hmpay.settlement

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(SettlementConfigurationProperties::class)
class SettlementConfiguration
