ext{
    axonVersion = "4.9.1"
}

group = 'com.hmpay.membership'
version = '0.0.1-SNAPSHOT'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation group: 'org.axonframework', name: 'axon-configuration', version: "$axonVersion"
    implementation group: 'org.axonframework', name: 'axon-spring-boot-starter', version: "$axonVersion"
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation project(path: ':common')
    implementation 'org.jetbrains:annotations:23.0.0'
    // runtimeOnly 'com.h2database:h2'
    implementation 'com.mysql:mysql-connector-j:8.3.0'
}

