server:
  port: 11101
  shutdown: graceful
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hm_pay?useSSL=false&allowPublicKeyRetrieval=true
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true